export type RunwayLengthCategory = 'Short' | 'Medium' | 'Long'
export type AirportComplexity = 'Low' | 'Medium' | 'High'
export type RunwaySurface = 'Asphalt' | 'Concrete' | 'Unknown'

export interface AirportProfile {
  icao: string
  iata: string
  name: string
  city: string
  country: string
  latitude: number
  longitude: number
  elevationFt?: number
  runwayLengthCategory: RunwayLengthCategory
  longestRunwayFt?: number
  runwaySurface: RunwaySurface
  complexity: AirportComplexity
  sourceLabel: string
}

const DEFAULT_SOURCE_LABEL = 'OurAirports local dataset / curated public airport profile'

const AIRPORT_DATABASE: Record<string, AirportProfile> = {
  KJFK: {
    icao: 'KJFK',
    iata: 'JFK',
    name: 'John F. Kennedy International',
    city: 'New York',
    country: 'USA',
    latitude: 40.6413,
    longitude: -73.7781,
    elevationFt: 13,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 14511,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KLAX: {
    icao: 'KLAX',
    iata: 'LAX',
    name: 'Los Angeles International',
    city: 'Los Angeles',
    country: 'USA',
    latitude: 33.9416,
    longitude: -118.4085,
    elevationFt: 125,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12091,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KSFO: {
    icao: 'KSFO',
    iata: 'SFO',
    name: 'San Francisco International',
    city: 'San Francisco',
    country: 'USA',
    latitude: 37.6213,
    longitude: -122.3790,
    elevationFt: 13,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11870,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KORD: {
    icao: 'KORD',
    iata: 'ORD',
    name: 'Chicago O\'Hare International',
    city: 'Chicago',
    country: 'USA',
    latitude: 41.9742,
    longitude: -87.9073,
    elevationFt: 668,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13000,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KATL: {
    icao: 'KATL',
    iata: 'ATL',
    name: 'Hartsfield-Jackson Atlanta International',
    city: 'Atlanta',
    country: 'USA',
    latitude: 33.6407,
    longitude: -84.4277,
    elevationFt: 1026,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12390,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KDFW: {
    icao: 'KDFW',
    iata: 'DFW',
    name: 'Dallas/Fort Worth International',
    city: 'Dallas',
    country: 'USA',
    latitude: 32.8998,
    longitude: -97.0403,
    elevationFt: 607,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13401,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KDEN: {
    icao: 'KDEN',
    iata: 'DEN',
    name: 'Denver International',
    city: 'Denver',
    country: 'USA',
    latitude: 39.8561,
    longitude: -104.6737,
    elevationFt: 5431,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 16000,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KSEA: {
    icao: 'KSEA',
    iata: 'SEA',
    name: 'Seattle-Tacoma International',
    city: 'Seattle',
    country: 'USA',
    latitude: 47.4502,
    longitude: -122.3088,
    elevationFt: 433,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11901,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KPHX: {
    icao: 'KPHX',
    iata: 'PHX',
    name: 'Phoenix Sky Harbor International',
    city: 'Phoenix',
    country: 'USA',
    latitude: 33.4342,
    longitude: -112.0080,
    elevationFt: 1135,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11489,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KLAS: {
    icao: 'KLAS',
    iata: 'LAS',
    name: 'Harry Reid International',
    city: 'Las Vegas',
    country: 'USA',
    latitude: 36.0840,
    longitude: -115.1537,
    elevationFt: 2181,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 14505,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KMIA: {
    icao: 'KMIA',
    iata: 'MIA',
    name: 'Miami International',
    city: 'Miami',
    country: 'USA',
    latitude: 25.7959,
    longitude: -80.2870,
    elevationFt: 8,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13016,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  EGLL: {
    icao: 'EGLL',
    iata: 'LHR',
    name: 'Heathrow',
    city: 'London',
    country: 'UK',
    latitude: 51.4700,
    longitude: -0.4543,
    elevationFt: 83,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12802,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  LFPG: {
    icao: 'LFPG',
    iata: 'CDG',
    name: 'Charles de Gaulle',
    city: 'Paris',
    country: 'France',
    latitude: 49.0097,
    longitude: 2.5479,
    elevationFt: 392,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13812,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  EDDF: {
    icao: 'EDDF',
    iata: 'FRA',
    name: 'Frankfurt Airport',
    city: 'Frankfurt',
    country: 'Germany',
    latitude: 50.0333,
    longitude: 8.5705,
    elevationFt: 364,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13123,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  EHAM: {
    icao: 'EHAM',
    iata: 'AMS',
    name: 'Amsterdam Airport Schiphol',
    city: 'Amsterdam',
    country: 'Netherlands',
    latitude: 52.3105,
    longitude: 4.7683,
    elevationFt: -11,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12467,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  LEMD: {
    icao: 'LEMD',
    iata: 'MAD',
    name: 'Adolfo Suárez Madrid–Barajas',
    city: 'Madrid',
    country: 'Spain',
    latitude: 40.4839,
    longitude: -3.5680,
    elevationFt: 1998,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13710,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  OMDB: {
    icao: 'OMDB',
    iata: 'DXB',
    name: 'Dubai International',
    city: 'Dubai',
    country: 'UAE',
    latitude: 25.2532,
    longitude: 55.3657,
    elevationFt: 62,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 14435,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  OTHH: {
    icao: 'OTHH',
    iata: 'DOH',
    name: 'Hamad International',
    city: 'Doha',
    country: 'Qatar',
    latitude: 25.2731,
    longitude: 51.6081,
    elevationFt: 13,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 15912,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  OMAD: {
    icao: 'OMAD',
    iata: 'AUH',
    name: 'Abu Dhabi International',
    city: 'Abu Dhabi',
    country: 'UAE',
    latitude: 24.4330,
    longitude: 54.6511,
    elevationFt: 88,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13451,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  LTFM: {
    icao: 'LTFM',
    iata: 'IST',
    name: 'Istanbul Airport',
    city: 'Istanbul',
    country: 'Turkey',
    latitude: 41.2753,
    longitude: 28.7519,
    elevationFt: 325,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13451,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  OJAI: {
    icao: 'OJAI',
    iata: 'AMM',
    name: 'Queen Alia International',
    city: 'Amman',
    country: 'Jordan',
    latitude: 31.7226,
    longitude: 35.9932,
    elevationFt: 2363,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12008,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  RJTT: {
    icao: 'RJTT',
    iata: 'HND',
    name: 'Tokyo Haneda',
    city: 'Tokyo',
    country: 'Japan',
    latitude: 35.5494,
    longitude: 139.7798,
    elevationFt: 21,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11024,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  RJAA: {
    icao: 'RJAA',
    iata: 'NRT',
    name: 'Narita International',
    city: 'Tokyo',
    country: 'Japan',
    latitude: 35.7647,
    longitude: 140.3863,
    elevationFt: 141,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13123,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  VHHH: {
    icao: 'VHHH',
    iata: 'HKG',
    name: 'Hong Kong International',
    city: 'Hong Kong',
    country: 'Hong Kong',
    latitude: 22.3080,
    longitude: 113.9185,
    elevationFt: 28,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12467,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  WSSS: {
    icao: 'WSSS',
    iata: 'SIN',
    name: 'Singapore Changi',
    city: 'Singapore',
    country: 'Singapore',
    latitude: 1.3644,
    longitude: 103.9915,
    elevationFt: 22,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13123,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  ZBAA: {
    icao: 'ZBAA',
    iata: 'PEK',
    name: 'Beijing Capital International',
    city: 'Beijing',
    country: 'China',
    latitude: 40.0799,
    longitude: 116.6031,
    elevationFt: 115,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12467,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  ZSPD: {
    icao: 'ZSPD',
    iata: 'PVG',
    name: 'Shanghai Pudong International',
    city: 'Shanghai',
    country: 'China',
    latitude: 31.1434,
    longitude: 121.8052,
    elevationFt: 13,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13123,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  ZGGG: {
    icao: 'ZGGG',
    iata: 'CAN',
    name: 'Guangzhou Baiyun International',
    city: 'Guangzhou',
    country: 'China',
    latitude: 28.3891,
    longitude: 113.2988,
    elevationFt: 50,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12467,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  RKSI: {
    icao: 'RKSI',
    iata: 'ICN',
    name: 'Incheon International',
    city: 'Seoul',
    country: 'South Korea',
    latitude: 37.4602,
    longitude: 126.4407,
    elevationFt: 23,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13123,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  VTBS: {
    icao: 'VTBS',
    iata: 'BKK',
    name: 'Suvarnabhumi Airport',
    city: 'Bangkok',
    country: 'Thailand',
    latitude: 13.6811,
    longitude: 100.7473,
    elevationFt: 5,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13123,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  WMKK: {
    icao: 'WMKK',
    iata: 'KUL',
    name: 'Kuala Lumpur International',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    latitude: 2.7456,
    longitude: 101.7099,
    elevationFt: 69,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13123,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  VIDP: {
    icao: 'VIDP',
    iata: 'DEL',
    name: 'Indira Gandhi International',
    city: 'New Delhi',
    country: 'India',
    latitude: 28.5562,
    longitude: 77.1000,
    elevationFt: 777,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 14521,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  VABB: {
    icao: 'VABB',
    iata: 'BOM',
    name: 'Chhatrapati Shivaji Maharaj International',
    city: 'Mumbai',
    country: 'India',
    latitude: 19.0896,
    longitude: 72.8656,
    elevationFt: 37,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12001,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  YSSY: {
    icao: 'YSSY',
    iata: 'SYD',
    name: 'Sydney Kingsford Smith',
    city: 'Sydney',
    country: 'Australia',
    latitude: -33.9399,
    longitude: 151.1753,
    elevationFt: 21,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12999,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  YMML: {
    icao: 'YMML',
    iata: 'MEL',
    name: 'Melbourne Airport',
    city: 'Melbourne',
    country: 'Australia',
    latitude: -37.6690,
    longitude: 144.8410,
    elevationFt: 434,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11998,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  YBBN: {
    icao: 'YBBN',
    iata: 'BNE',
    name: 'Brisbane Airport',
    city: 'Brisbane',
    country: 'Australia',
    latitude: -27.3842,
    longitude: 153.1175,
    elevationFt: 13,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11483,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  NZAA: {
    icao: 'NZAA',
    iata: 'AKL',
    name: 'Auckland Airport',
    city: 'Auckland',
    country: 'New Zealand',
    latitude: -37.0082,
    longitude: 174.7915,
    elevationFt: 23,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11926,
    runwaySurface: 'Concrete',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  CYYZ: {
    icao: 'CYYZ',
    iata: 'YYZ',
    name: 'Toronto Pearson International',
    city: 'Toronto',
    country: 'Canada',
    latitude: 43.6777,
    longitude: -79.6248,
    elevationFt: 569,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11120,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  SBGR: {
    icao: 'SBGR',
    iata: 'GRU',
    name: 'São Paulo/Guarulhos International',
    city: 'São Paulo',
    country: 'Brazil',
    latitude: -23.4356,
    longitude: -46.4731,
    elevationFt: 2459,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12139,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  SAEZ: {
    icao: 'SAEZ',
    iata: 'EZE',
    name: 'Ministro Pistarini International',
    city: 'Buenos Aires',
    country: 'Argentina',
    latitude: -34.8222,
    longitude: -58.5358,
    elevationFt: 67,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10827,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  SCEL: {
    icao: 'SCEL',
    iata: 'SCL',
    name: 'Arturo Merino Benítez International',
    city: 'Santiago',
    country: 'Chile',
    latitude: -33.3930,
    longitude: -70.7858,
    elevationFt: 1555,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12303,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  MMMX: {
    icao: 'MMMX',
    iata: 'MEX',
    name: 'Mexico City International',
    city: 'Mexico City',
    country: 'Mexico',
    latitude: 19.4361,
    longitude: -99.0719,
    elevationFt: 7316,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12730,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  MMUN: {
    icao: 'MMUN',
    iata: 'CUN',
    name: 'Cancún International',
    city: 'Cancún',
    country: 'Mexico',
    latitude: 21.0365,
    longitude: -86.8771,
    elevationFt: 20,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11483,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  FAOR: {
    icao: 'FAOR',
    iata: 'JNB',
    name: 'O. R. Tambo International',
    city: 'Johannesburg',
    country: 'South Africa',
    latitude: -26.1392,
    longitude: 28.2460,
    elevationFt: 5558,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 14495,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  FACT: {
    icao: 'FACT',
    iata: 'CPT',
    name: 'Cape Town International',
    city: 'Cape Town',
    country: 'South Africa',
    latitude: -33.9715,
    longitude: 18.6021,
    elevationFt: 151,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10502,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  UUDD: {
    icao: 'UUDD',
    iata: 'DME',
    name: 'Domodedovo International',
    city: 'Moscow',
    country: 'Russia',
    latitude: 55.4086,
    longitude: 37.9061,
    elevationFt: 588,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12444,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  UUEE: {
    icao: 'UUEE',
    iata: 'SVO',
    name: 'Sheremetyevo International',
    city: 'Moscow',
    country: 'Russia',
    latitude: 55.9726,
    longitude: 37.4146,
    elevationFt: 622,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12139,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  LIRF: {
    icao: 'LIRF',
    iata: 'FCO',
    name: 'Leonardo da Vinci–Fiumicino International',
    city: 'Rome',
    country: 'Italy',
    latitude: 41.8003,
    longitude: 12.2389,
    elevationFt: 14,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12802,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  EBBR: {
    icao: 'EBBR',
    iata: 'BRU',
    name: 'Brussels Airport',
    city: 'Brussels',
    country: 'Belgium',
    latitude: 50.9014,
    longitude: 4.4844,
    elevationFt: 184,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11936,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  LOWW: {
    icao: 'LOWW',
    iata: 'VIE',
    name: 'Vienna International',
    city: 'Vienna',
    country: 'Austria',
    latitude: 48.1103,
    longitude: 16.5697,
    elevationFt: 600,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11811,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  LSZH: {
    icao: 'LSZH',
    iata: 'ZRH',
    name: 'Zurich Airport',
    city: 'Zurich',
    country: 'Switzerland',
    latitude: 47.4647,
    longitude: 8.5492,
    elevationFt: 1416,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12139,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  EKCH: {
    icao: 'EKCH',
    iata: 'CPH',
    name: 'Copenhagen Airport',
    city: 'Copenhagen',
    country: 'Denmark',
    latitude: 55.6179,
    longitude: 12.6560,
    elevationFt: 17,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11811,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  ESSA: {
    icao: 'ESSA',
    iata: 'ARN',
    name: 'Stockholm Arlanda',
    city: 'Stockholm',
    country: 'Sweden',
    latitude: 59.6519,
    longitude: 17.9186,
    elevationFt: 137,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10827,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  ENGM: {
    icao: 'ENGM',
    iata: 'OSL',
    name: 'Oslo Gardermoen',
    city: 'Oslo',
    country: 'Norway',
    latitude: 60.1975,
    longitude: 11.1004,
    elevationFt: 681,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11811,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  EFHK: {
    icao: 'EFHK',
    iata: 'HEL',
    name: 'Helsinki Vantaa',
    city: 'Helsinki',
    country: 'Finland',
    latitude: 60.3172,
    longitude: 24.9633,
    elevationFt: 179,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11483,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  LEBL: {
    icao: 'LEBL',
    iata: 'BCN',
    name: 'Josep Tarradellas Barcelona–El Prat',
    city: 'Barcelona',
    country: 'Spain',
    latitude: 41.2974,
    longitude: 2.0833,
    elevationFt: 12,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12280,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  LPPT: {
    icao: 'LPPT',
    iata: 'LIS',
    name: 'Humberto Delgado Airport',
    city: 'Lisbon',
    country: 'Portugal',
    latitude: 38.7742,
    longitude: -9.1342,
    elevationFt: 374,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12484,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  OKBK: {
    icao: 'OKBK',
    iata: 'KWI',
    name: 'Kuwait International',
    city: 'Kuwait City',
    country: 'Kuwait',
    latitude: 29.2266,
    longitude: 47.9689,
    elevationFt: 206,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11483,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  OBBI: {
    icao: 'OBBI',
    iata: 'BAH',
    name: 'Bahrain International',
    city: 'Manama',
    country: 'Bahrain',
    latitude: 26.2708,
    longitude: 50.6336,
    elevationFt: 6,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12992,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  OOMS: {
    icao: 'OOMS',
    iata: 'MCT',
    name: 'Muscat International',
    city: 'Muscat',
    country: 'Oman',
    latitude: 23.5933,
    longitude: 58.2844,
    elevationFt: 48,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13123,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  OEJN: {
    icao: 'OEJN',
    iata: 'JED',
    name: 'King Abdulaziz International',
    city: 'Jeddah',
    country: 'Saudi Arabia',
    latitude: 21.6796,
    longitude: 39.1565,
    elevationFt: 58,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13123,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  OERK: {
    icao: 'OERK',
    iata: 'RUH',
    name: 'King Khalid International',
    city: 'Riyadh',
    country: 'Saudi Arabia',
    latitude: 24.9576,
    longitude: 46.6988,
    elevationFt: 2049,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13796,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  LLBG: {
    icao: 'LLBG',
    iata: 'TLV',
    name: 'Ben Gurion International',
    city: 'Tel Aviv',
    country: 'Israel',
    latitude: 32.0094,
    longitude: 34.8769,
    elevationFt: 135,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13320,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  VVTS: {
    icao: 'VVTS',
    iata: 'SGN',
    name: 'Tan Son Nhat International',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    latitude: 10.8188,
    longitude: 106.6519,
    elevationFt: 33,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12467,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  RPLL: {
    icao: 'RPLL',
    iata: 'MNL',
    name: 'Ninoy Aquino International',
    city: 'Manila',
    country: 'Philippines',
    latitude: 14.5086,
    longitude: 121.0194,
    elevationFt: 75,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12261,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  WIII: {
    icao: 'WIII',
    iata: 'CGK',
    name: 'Soekarno–Hatta International',
    city: 'Jakarta',
    country: 'Indonesia',
    latitude: -6.1256,
    longitude: 106.6558,
    elevationFt: 34,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12008,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  RCTP: {
    icao: 'RCTP',
    iata: 'TPE',
    name: 'Taiwan Taoyuan International',
    city: 'Taipei',
    country: 'Taiwan',
    latitude: 25.0777,
    longitude: 121.2328,
    elevationFt: 108,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12467,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  VOBL: {
    icao: 'VOBL',
    iata: 'BLR',
    name: 'Kempegowda International',
    city: 'Bangalore',
    country: 'India',
    latitude: 13.1986,
    longitude: 77.7066,
    elevationFt: 3002,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13123,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  VOMM: {
    icao: 'VOMM',
    iata: 'MAA',
    name: 'Chennai International',
    city: 'Chennai',
    country: 'India',
    latitude: 12.9941,
    longitude: 80.1708,
    elevationFt: 52,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12001,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  YPPH: {
    icao: 'YPPH',
    iata: 'PER',
    name: 'Perth Airport',
    city: 'Perth',
    country: 'Australia',
    latitude: -31.9403,
    longitude: 115.9667,
    elevationFt: 67,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11299,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  NZCH: {
    icao: 'NZCH',
    iata: 'CHC',
    name: 'Christchurch International',
    city: 'Christchurch',
    country: 'New Zealand',
    latitude: -43.4894,
    longitude: 172.5322,
    elevationFt: 123,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10784,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  CYUL: {
    icao: 'CYUL',
    iata: 'YUL',
    name: 'Montréal–Trudeau International',
    city: 'Montreal',
    country: 'Canada',
    latitude: 45.4706,
    longitude: -73.7408,
    elevationFt: 118,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11000,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  CYVR: {
    icao: 'CYVR',
    iata: 'YVR',
    name: 'Vancouver International',
    city: 'Vancouver',
    country: 'Canada',
    latitude: 49.1967,
    longitude: -123.1815,
    elevationFt: 14,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11500,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  CYYC: {
    icao: 'CYYC',
    iata: 'YYC',
    name: 'Calgary International',
    city: 'Calgary',
    country: 'Canada',
    latitude: 51.1139,
    longitude: -114.0203,
    elevationFt: 3557,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 14000,
    runwaySurface: 'Concrete',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  SKBO: {
    icao: 'SKBO',
    iata: 'BOG',
    name: 'El Dorado International',
    city: 'Bogota',
    country: 'Colombia',
    latitude: 4.7017,
    longitude: -74.1469,
    elevationFt: 8361,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12467,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  MPTO: {
    icao: 'MPTO',
    iata: 'PTY',
    name: 'Tocumen International',
    city: 'Panama City',
    country: 'Panama',
    latitude: 9.0714,
    longitude: -79.3835,
    elevationFt: 85,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10007,
    runwaySurface: 'Concrete',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  HECA: {
    icao: 'HECA',
    iata: 'CAI',
    name: 'Cairo International',
    city: 'Cairo',
    country: 'Egypt',
    latitude: 30.1219,
    longitude: 31.4056,
    elevationFt: 382,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13120,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  HAAB: {
    icao: 'HAAB',
    iata: 'ADD',
    name: 'Addis Ababa Bole International',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    latitude: 8.9778,
    longitude: 38.7993,
    elevationFt: 7625,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12467,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  DNMM: {
    icao: 'DNMM',
    iata: 'LOS',
    name: 'Murtala Muhammed International',
    city: 'Lagos',
    country: 'Nigeria',
    latitude: 6.5774,
    longitude: 3.3210,
    elevationFt: 135,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12795,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  HKJK: {
    icao: 'HKJK',
    iata: 'NBO',
    name: 'Jomo Kenyatta International',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3192,
    longitude: 36.9275,
    elevationFt: 5330,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 13507,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  GMMN: {
    icao: 'GMMN',
    iata: 'CMN',
    name: 'Mohammed V International',
    city: 'Casablanca',
    country: 'Morocco',
    latitude: 33.3675,
    longitude: -7.5899,
    elevationFt: 656,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12205,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KMCO: {
    icao: 'KMCO',
    iata: 'MCO',
    name: 'Orlando International',
    city: 'Orlando',
    country: 'USA',
    latitude: 28.4289,
    longitude: -81.3090,
    elevationFt: 96,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12005,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KEWR: {
    icao: 'KEWR',
    iata: 'EWR',
    name: 'Newark Liberty International',
    city: 'Newark',
    country: 'USA',
    latitude: 40.6895,
    longitude: -74.1745,
    elevationFt: 18,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11000,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KCLT: {
    icao: 'KCLT',
    iata: 'CLT',
    name: 'Charlotte Douglas International',
    city: 'Charlotte',
    country: 'USA',
    latitude: 35.2140,
    longitude: -80.9431,
    elevationFt: 748,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10000,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KIAH: {
    icao: 'KIAH',
    iata: 'IAH',
    name: 'George Bush Intercontinental',
    city: 'Houston',
    country: 'USA',
    latitude: 29.9804,
    longitude: -95.3397,
    elevationFt: 97,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12002,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KBOS: {
    icao: 'KBOS',
    iata: 'BOS',
    name: 'General Edward Lawrence Logan International',
    city: 'Boston',
    country: 'USA',
    latitude: 42.3643,
    longitude: -71.0052,
    elevationFt: 20,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10083,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KMSP: {
    icao: 'KMSP',
    iata: 'MSP',
    name: 'Minneapolis–Saint Paul International',
    city: 'Minneapolis',
    country: 'USA',
    latitude: 44.8848,
    longitude: -93.2223,
    elevationFt: 841,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11006,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KDTW: {
    icao: 'KDTW',
    iata: 'DTW',
    name: 'Detroit Metropolitan Wayne County',
    city: 'Detroit',
    country: 'USA',
    latitude: 42.2124,
    longitude: -83.3533,
    elevationFt: 645,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12003,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KSLC: {
    icao: 'KSLC',
    iata: 'SLC',
    name: 'Salt Lake City International',
    city: 'Salt Lake City',
    country: 'USA',
    latitude: 40.7899,
    longitude: -111.9791,
    elevationFt: 4227,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12002,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KPHL: {
    icao: 'KPHL',
    iata: 'PHL',
    name: 'Philadelphia International',
    city: 'Philadelphia',
    country: 'USA',
    latitude: 39.8719,
    longitude: -75.2411,
    elevationFt: 36,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12000,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KBWI: {
    icao: 'KBWI',
    iata: 'BWI',
    name: 'Baltimore/Washington International Thurgood Marshall',
    city: 'Baltimore',
    country: 'USA',
    latitude: 39.1754,
    longitude: -76.6683,
    elevationFt: 146,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10502,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KTPA: {
    icao: 'KTPA',
    iata: 'TPA',
    name: 'Tampa International',
    city: 'Tampa',
    country: 'USA',
    latitude: 27.9755,
    longitude: -82.5332,
    elevationFt: 26,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11002,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KSAN: {
    icao: 'KSAN',
    iata: 'SAN',
    name: 'San Diego International',
    city: 'San Diego',
    country: 'USA',
    latitude: 32.7336,
    longitude: -117.1897,
    elevationFt: 17,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 9401,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KIAD: {
    icao: 'KIAD',
    iata: 'IAD',
    name: 'Washington Dulles International',
    city: 'Washington D.C.',
    country: 'USA',
    latitude: 38.9445,
    longitude: -77.4558,
    elevationFt: 313,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11500,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KDCA: {
    icao: 'KDCA',
    iata: 'DCA',
    name: 'Ronald Reagan Washington National',
    city: 'Washington D.C.',
    country: 'USA',
    latitude: 38.8512,
    longitude: -77.0377,
    elevationFt: 15,
    runwayLengthCategory: 'Medium',
    longestRunwayFt: 7169,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KMDW: {
    icao: 'KMDW',
    iata: 'MDW',
    name: 'Chicago Midway International',
    city: 'Chicago',
    country: 'USA',
    latitude: 41.7860,
    longitude: -87.7524,
    elevationFt: 620,
    runwayLengthCategory: 'Medium',
    longestRunwayFt: 6522,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KPDX: {
    icao: 'KPDX',
    iata: 'PDX',
    name: 'Portland International',
    city: 'Portland',
    country: 'USA',
    latitude: 45.5886,
    longitude: -122.5975,
    elevationFt: 31,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11000,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KAUS: {
    icao: 'KAUS',
    iata: 'AUS',
    name: 'Austin–Bergstrom International',
    city: 'Austin',
    country: 'USA',
    latitude: 30.1945,
    longitude: -97.6699,
    elevationFt: 542,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12250,
    runwaySurface: 'Concrete',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KBNA: {
    icao: 'KBNA',
    iata: 'BNA',
    name: 'Nashville International',
    city: 'Nashville',
    country: 'USA',
    latitude: 36.1245,
    longitude: -86.6782,
    elevationFt: 599,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11030,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KRDU: {
    icao: 'KRDU',
    iata: 'RDU',
    name: 'Raleigh–Durham International',
    city: 'Raleigh',
    country: 'USA',
    latitude: 35.8776,
    longitude: -78.7875,
    elevationFt: 435,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10000,
    runwaySurface: 'Concrete',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KMSY: {
    icao: 'KMSY',
    iata: 'MSY',
    name: 'Louis Armstrong New Orleans International',
    city: 'New Orleans',
    country: 'USA',
    latitude: 29.9934,
    longitude: -90.2580,
    elevationFt: 4,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10104,
    runwaySurface: 'Concrete',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KIND: {
    icao: 'KIND',
    iata: 'IND',
    name: 'Indianapolis International',
    city: 'Indianapolis',
    country: 'USA',
    latitude: 39.7173,
    longitude: -86.2941,
    elevationFt: 797,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11200,
    runwaySurface: 'Concrete',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KCLE: {
    icao: 'KCLE',
    iata: 'CLE',
    name: 'Cleveland Hopkins International',
    city: 'Cleveland',
    country: 'USA',
    latitude: 41.4108,
    longitude: -81.8494,
    elevationFt: 791,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 9956,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KCMH: {
    icao: 'KCMH',
    iata: 'CMH',
    name: 'John Glenn Columbus International',
    city: 'Columbus',
    country: 'USA',
    latitude: 39.9980,
    longitude: -82.8919,
    elevationFt: 815,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10113,
    runwaySurface: 'Asphalt',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KCVG: {
    icao: 'KCVG',
    iata: 'CVG',
    name: 'Cincinnati/Northern Kentucky International',
    city: 'Cincinnati',
    country: 'USA',
    latitude: 39.0461,
    longitude: -84.6622,
    elevationFt: 896,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 12000,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KSTL: {
    icao: 'KSTL',
    iata: 'STL',
    name: 'St. Louis Lambert International',
    city: 'St. Louis',
    country: 'USA',
    latitude: 38.7477,
    longitude: -90.3597,
    elevationFt: 618,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11020,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KMCI: {
    icao: 'KMCI',
    iata: 'MCI',
    name: 'Kansas City International',
    city: 'Kansas City',
    country: 'USA',
    latitude: 39.2976,
    longitude: -94.7139,
    elevationFt: 1026,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 10801,
    runwaySurface: 'Concrete',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KSMF: {
    icao: 'KSMF',
    iata: 'SMF',
    name: 'Sacramento International',
    city: 'Sacramento',
    country: 'USA',
    latitude: 38.6954,
    longitude: -121.5908,
    elevationFt: 27,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 8605,
    runwaySurface: 'Concrete',
    complexity: 'Medium',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KSJC: {
    icao: 'KSJC',
    iata: 'SJC',
    name: 'San Jose Mineta International',
    city: 'San Jose',
    country: 'USA',
    latitude: 37.3619,
    longitude: -121.9290,
    elevationFt: 62,
    runwayLengthCategory: 'Long',
    longestRunwayFt: 11000,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KSNA: {
    icao: 'KSNA',
    iata: 'SNA',
    name: 'John Wayne Airport-Orange County',
    city: 'Santa Ana',
    country: 'USA',
    latitude: 33.6757,
    longitude: -117.8675,
    elevationFt: 56,
    runwayLengthCategory: 'Short',
    longestRunwayFt: 5701,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  KASE: {
    icao: 'KASE',
    iata: 'ASE',
    name: 'Aspen-Pitkin County',
    city: 'Aspen',
    country: 'USA',
    latitude: 39.2232,
    longitude: -106.8690,
    elevationFt: 7820,
    runwayLengthCategory: 'Medium',
    longestRunwayFt: 8006,
    runwaySurface: 'Asphalt',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  },
  EGLC: {
    icao: 'EGLC',
    iata: 'LCY',
    name: 'London City',
    city: 'London',
    country: 'UK',
    latitude: 51.5053,
    longitude: 0.0553,
    elevationFt: 19,
    runwayLengthCategory: 'Short',
    longestRunwayFt: 4948,
    runwaySurface: 'Concrete',
    complexity: 'High',
    sourceLabel: DEFAULT_SOURCE_LABEL,
  }
}

/**
 * Get an airport by its ICAO code. Returns null if not found.
 */
export function getAirportByIcao(icao: string): AirportProfile | null {
  const code = icao.toUpperCase().trim()
  return AIRPORT_DATABASE[code] || null
}

/**
 * Old wrapper to keep backwards compatibility locally if needed.
 */
export function getAirportProfile(icao: string): AirportProfile | null {
  return getAirportByIcao(icao)
}

/**
 * Search airports by ICAO, IATA, Name, or City.
 */
export function searchAirports(query: string): AirportProfile[] {
  const q = query.toLowerCase().trim()
  if (!q) return []
  return Object.values(AIRPORT_DATABASE).filter(a => 
    a.icao.toLowerCase().includes(q) ||
    (a.iata && a.iata.toLowerCase().includes(q)) ||
    a.name.toLowerCase().includes(q) ||
    a.city.toLowerCase().includes(q)
  )
}

/**
 * Calculate distance between two lat/lon coordinates in kilometers using the Haversine formula.
 */
export function calculateDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371 // Radius of the earth in km
  const dLat = deg2rad(lat2 - lat1)
  const dLon = deg2rad(lon2 - lon1) 
  const a = 
    Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * 
    Math.sin(dLon/2) * Math.sin(dLon/2)
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)) 
  const d = R * c // Distance in km
  return d
}

function deg2rad(deg: number): number {
  return deg * (Math.PI/180)
}

/**
 * Get the nearest N airports to a given latitude and longitude.
 */
export function getNearestAirports(lat: number, lon: number, limit: number = 5): AirportProfile[] {
  const airportsWithDistance = Object.values(AIRPORT_DATABASE).map(airport => {
    return {
      airport,
      distance: calculateDistanceKm(lat, lon, airport.latitude, airport.longitude)
    }
  })

  airportsWithDistance.sort((a, b) => a.distance - b.distance)

  return airportsWithDistance.slice(0, limit).map(item => item.airport)
}
